"""add prefecture_capital value to city table

Revision ID: 6d96bc27904e
Revises: a770d5ae3c92
Create Date: 2026-02-07 11:53:34.520693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d96bc27904e'
down_revision = 'a770d5ae3c92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prefecture_capital', sa.Boolean(), server_default=sa.text('(false)'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.drop_column('prefecture_capital')

    # ### end Alembic commands ###
