"""add cities table

Revision ID: a770d5ae3c92
Revises: a7d9bf6e1568
Create Date: 2026-02-07 11:42:52.411593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a770d5ae3c92'
down_revision = 'a7d9bf6e1568'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('prefecture_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('japanese_spelling', sa.String(), nullable=False),
    sa.Column('japanese_name', sa.String(), nullable=False),
    sa.Column('img', sa.String(), nullable=False),
    sa.Column('card_img', sa.String(), nullable=False),
    sa.Column('banner_img', sa.String(), nullable=True),
    sa.Column('info', sa.String(), nullable=False),
    sa.Column('population', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['prefecture_id'], ['prefectures.id'], name=op.f('fk_cities_prefecture_id_prefectures')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cities')
    # ### end Alembic commands ###
