"""initial migration

Revision ID: a7d9bf6e1568
Revises: 
Create Date: 2026-02-06 17:25:58.467011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7d9bf6e1568'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prefectures',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('flag', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('japanese_spelling', sa.String(), nullable=False),
    sa.Column('japanese_name', sa.String(), nullable=False),
    sa.Column('img', sa.String(), nullable=False),
    sa.Column('card_img', sa.String(), nullable=False),
    sa.Column('banner_img', sa.String(), nullable=True),
    sa.Column('info', sa.String(), nullable=False),
    sa.Column('population', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flag'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prefectures')
    # ### end Alembic commands ###
